### ISSUE TITLE
error executing craft tweaker .zs files

### ISSUE THREAD

**Issue by schismatix** [TheDragonTeam/Custom-Crafting-Tables#3]
**Custom Crafting Tables Version**:
cct-1.11.2-1.2.0 and also 1.1.0
**TheDragonLib Version**:
thedragonlib-1.11.2-3.2.2
**MinecraftForge Version**:
forge-1.11.2-13.20.0.2228 up to 2312
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [ ] Client

Using:
**Forgelin-1.4.2**
**CraftTweaker-1.11.2-3.0.25**

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
no crash get the following error:

ERROR:error executing MasonryBench.zs: com/blamejared/mtlib/helpers/InputHelper

Masonry Bench.zs:

mods.cct.ThreeByThree.addShaped(<anvortheon:netherstonetileitem> * 4, [[null, <anvortheon:masonryhammer>], [<anvortheon:netherstonetilesingle>, <anvortheon:masonrychisel>]]);

Also tried with just the following recipe:
mods.cct.ThreeByThree.addShaped(minecraft:stick * 4, [[minecraft:planks], [minecraft:planks]]);
and still get the same error

**What happens / happened?**:
cant create recipes
**How can I reproduce it?**:
as above, creating items / blocks from mods or vanilla minecraft
**(Optional) Mod List**:
Anvortheon
Bibliocraft
Chisels and bits
storage Drawers
jei: jei_1.11.2-4.2.11.251 (old version due to comaptablity with minetweaker and furnace recipies not showing in later versions)

**Comment by schismatix** [comment]
Also tried with just the following recipe:
mods.cct.ThreeByThree.addShaped(<minecraft:stick> * 4, [[<minecraft:planks>], [<minecraft:planks>]]);

and still get the same error

**Comment by sokratis12GR** [comment]
Have you tried making the recipe.. 3x3 like add null for empty space

**Comment by sokratis12GR** [comment]
I'll look into that soon. For now please use null for empty space

**Comment by schismatix** [comment]
will do and thanks for quick response

**Comment by schismatix** [comment]
Using:
`mods.cct.ThreeByThree.addShaped(<minecraft:stick> * 4, [[null, null, null], [null, <minecraft:planks>, null], [<minecraft:planks>, null, null]]);`
or
`mods.cct.ThreeByThree.addShaped(<anvortheon:redsandstonetileitem> * 4, [[null, null, null], [null, <anvortheon:masonryhammer>.reuse(), null], [<anvortheon:redsandstonetilesingle>, <anvortheon:masonrychisel>.reuse(), null]]);`
still gives the error

**Comment by sokratis12GR** [comment]
Hmm could you try without the * 4

**Comment by schismatix** [comment]
even without the * 4 still gives the error

**Comment by schismatix** [comment]
also tried an item in every slot:
`mods.cct.ThreeByThree.addShaped(<minecraft:stick>, [[<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);`

and still gave error

**Comment by sokratis12GR** [comment]
That's strange... It worked fine for me while I was testing... Hmm will look into that once I'm back home (tomorrow or the day after).. 
Could you try one last thing!? 
Like first assigning a Val with the type of item and then using it. 
But thanks for the report!

**Comment by sokratis12GR** [comment]
Actually, it seems you are missing [MTLib](https://minecraft.curseforge.com/projects/mtlib)

**Comment by schismatix** [comment]
heh just tried:

`val` stick = <minecraft:stick>;
val plank = <minecraft:planks>;

mods.cct.ThreeByThree.addShaped(stick, [[plank, plank, plank], [plank, plank, plank], [plank, plank, plank]]);

and same error

hmmm mtlib ill check

**Comment by schismatix** [comment]
ok got it to work with mtlib :)

however I have found recipes using .reuse() and the transform extensions do not work also the recipes are not showing in jei although I am using an old version I will try with latest

might be worth putting on the page mtlib is required (also forgelin as I didn't realise it was needed till I loaded up minecraft).

Thanks for the quick replies and help

**Comment by sokratis12GR** [comment]
Yeah I'll put Forgelin as required but Ill try to make MTLib not required in the next update, so 1 there is less confusion and 2 less mods to download

**Comment by schismatix** [comment]
jei works with latest version (just annoying won't show custom furnace recipes with latest version)

and once again thanks
