### ISSUE TITLE
only 3x3 tables show in jei

### ISSUE THREAD

**Issue by schismatix** [TheDragonTeam/Custom-Crafting-Tables#4]
**Custom Crafting Tables Version**:
cct-1.11.2-1.2.1 also cct-1.11.2-1.2.0
**TheDragonLib Version**:
thedragonlib-1.11.2-3.2.2
**MinecraftForge Version**:
forge-1.11.2-13.20.0.2228 - forge-1.11.2-13.20.0.2314
**Minecraft Version**:
1.11.2
**Client or Server?**:
- [X ] Client

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
no crash

**What happens / happened?**:
only 3x3 table recipes show in jei all other sizes do not
not sure if its related but in jei log it actively un-adds them:
[SERVER][INFO] Un-adding 2x2 for Stone[SERVER_STOPPING]
The recipes still work just not shown in jei

**How can I reproduce it?**:
add a 2x2 recipe :)
**(Optional) Mod List**: 
taken all other mods out can reproduce just using minecraft items/blocks in recipes

**Comment by sokratis12GR** [comment]
Which Jei version are you using? 
- I should probably add it in the issue template next time xD

**Comment by schismatix** [comment]
tried with:
jei_1.11.2-4.4.0.277
jei_1.11.2-4.4.0.283 - jei_1.11.2-4.4.0.287

**Comment by sokratis12GR** [comment]
Interesting, could you show me the scripts you used, which CraftTweaker version.
The latest version of CCT was built using Jei 1.11.2-4.4.0.283, CT 3.0.24

**Comment by sokratis12GR** [comment]
Also, I'll release another update today updating the integrations to latest versions of jei and ct

**Comment by schismatix** [comment]
to test it I simply used:
mods.cct.TwoByTwo.addShaped(<minecraft:stone>, [[null, <minecraft:cobblestone>], [null, null]]);
with nothing else.
used Jei 1.11.2-4.4.0.283, cct-1.11.2-1.2.1, forge-1.11.2-13.20.0.2314, thedragonlib-1.11.2-3.2.2

**Comment by sokratis12GR** [comment]
Ah, 2x2 and 1x1 are the only ones without Jei integration

**Comment by schismatix** [comment]
typical....sorry I tried 1x1 and 2x2 and then stupidly assumed the rest were the same thinking that only 3x3 worked
