### ISSUE TITLE
is it possible for a 2x2 table to show in jei or have another 3x3 table

### ISSUE THREAD

**Issue by schismatix** [TheDragonTeam/Custom-Crafting-Tables#5]
Not an error but refers to: error executing craft tweaker .zs files #3 

**Custom Crafting Tables Version:**
cct-1.11.2-1.2.0 and also 1.1.0
**TheDragonLib Version:**
thedragonlib-1.11.2-3.2.2
**MinecraftForge Version:**
forge-1.11.2-13.20.0.2228 up to 2312
**Minecraft Version:**
1.11.2
**Client or Server?:**
[ ] Client
**Using:**
jei_1.11.2-4.2.11.251-283
Forgelin-1.4.2
CraftTweaker-1.11.2-3.0.25
**Crash Report (via. Pastebin):**
no crash - posted here as requested by KewaiiGamer on curse

Would it be possible to have two 3x3 crafting tables. I only ask this as the 2x2 doesn't show in jei?
 
Or an alternative question could be is it possible to make the 2x2 show in jei? :)

**Comment by sokratis12GR** [comment]
Its currently not possible to show the 1x1 and 2x2 recipes on jei.
Maybe in the future there will be another 3x3 table, but why ?

**Comment by schismatix** [comment]
The reason being so it is possible to restrict what can be made ie: normal crafting table, one crafting table made with emerald and final one with diamond. The last two are more difficult to get and restrict certain items/blocks until they can be made. (It sorta adds progression in a way)
I know I could just use the 4x4 but it just looks wrong to me, guess I'm so used to seeing the 3x3 grid. If its not that easy or just a pain to do (as I am the only one asking) then so be it a 4x4 it is :)

**Comment by sokratis12GR** [comment]
I'll see what I can do soon :)

**Comment by sokratis12GR** [comment]
I wasn't able to add it sorry, but this will not come. **Might** come in future but for now no.
