### ISSUE TITLE
[Feature Request] Support for inventory-like crafting tables

### ISSUE THREAD

**Issue by BluMasc** [TheDragonTeam/Custom-Crafting-Tables#6]
**Custom Crafting Tables Version**:1.3.0

**TheDragonLib Version**:3.2.2

**CraftTweaker Version**:3.0.26

**Just Enough Items Version**:4.5.0.295

**MinecraftForge Version**:13.20.1.2388

**Minecraft Version**:1.11.2

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: none

**What happens / happened?**: it's not realy a bug, but a logical issue, when you add a crafting recipe for the bigger crafting tables, it is very difficult to craft the items, as you can't have all ingredients at once in your inventory and all items drop, when you close the crafting window. Maybe making the crafting table having an inventory and keeping the items may be a solution.
Sorry if this is not the place to post this.

**How can I reproduce it?**: just make a recipe in a big enough crafting table that uses more than 36 different items.

**(Optional) Mod List**:

**Comment by sokratis12GR** [comment]
The idea and concept are nice. But thats a no for now. and I no longer support 1.11.2
So please if this is still a wanted thing re-create the Issue, for the 1.12.2 version and do not include issue information but more of:
[Feature Request] Support for inventory-like crafting tables
with description only what is wanted.
