### ISSUE TITLE
Bug with JEI and Crafttweaker

### ISSUE THREAD

**Issue by CobaltRealm** [TheDragonTeam/Custom-Crafting-Tables#7]
**Custom Crafting Tables Version**: 1.4.1

**TheDragonLib Version**: 3.3.0

**CraftTweaker Version**: 3.0.26

**Just Enough Items Version**: 4.5.0.294

**MinecraftForge Version**: 13.20.1.2476

**Minecraft Version**: 1.11.2

**What happens / happened?**: With crafttweaker I made a recipe for an item crafted in a 9x9 and also one in a 5x5, and when I press R to see the recipe the recipe doesnt show, but if I press the U in the materials required for the craft it shows the recipe

**How can I reproduce it?**: Create a recipe for a CCT and then check the recipe in JEI

**Comment by sokratis12GR** [comment]
Sorry no longer supporting 1.11.2 . But has been fixed for 1.12.2
